/**
 * Excel export for the Reports system.
 *
 * Renders a professional multi-sheet workbook from the same `ReportPayload`
 * the dashboard uses, so exported figures always match the on-screen report.
 * Runs on the server (Node) where exceljs is available.
 */
import ExcelJS from "exceljs";
import {
  formatReportDateTime,
  periodRangeLabel,
  reportFileName,
  statusLabel,
  type ReportPayload,
} from "@/lib/reports";
import type { ExportResult } from "@/lib/reports.functions";

const MONEY_FMT = "#,##0.00";
const DATE_FMT = "dd mmm yyyy hh:mm";
const HEADER_FILL = "FF0F5132";
const TOTAL_FILL = "FFE7F0EA";
const BORDER = { style: "thin" as const, color: { argb: "FFD9E2DC" } };

const currency = (value: number) => Number(value ?? 0);

function styleHeader(sheet: ExcelJS.Worksheet, columns: number, rowNumber = 1) {
  const row = sheet.getRow(rowNumber);
  for (let i = 1; i <= columns; i++) {
    const cell = row.getCell(i);
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_FILL } };
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = { top: BORDER, left: BORDER, bottom: BORDER, right: BORDER };
  }
  row.height = 20;
  sheet.views = [{ state: "frozen", ySplit: rowNumber }];
}

function addTitle(sheet: ExcelJS.Worksheet, title: string, subtitle: string) {
  sheet.mergeCells("A1:D1");
  const titleCell = sheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { bold: true, size: 14, color: { argb: "FF0F5132" } };
  sheet.getCell("A2").value = subtitle;
  sheet.getCell("A2").font = { size: 10, color: { argb: "FF6B7280" } };
  sheet.getRow(1).height = 22;
}

function addTotalRow(sheet: ExcelJS.Worksheet, label: string, totals: Record<number, number>) {
  const row = sheet.addRow([label]);
  for (const [colIndex, value] of Object.entries(totals)) {
    row.getCell(Number(colIndex)).value = currency(value);
    row.getCell(Number(colIndex)).numFmt = MONEY_FMT;
  }
  row.font = { bold: true };
  for (let i = 1; i <= sheet.columnCount; i++) {
    row.getCell(i).fill = { type: "pattern", pattern: "solid", fgColor: { argb: TOTAL_FILL } };
    row.getCell(i).border = { top: BORDER, bottom: BORDER };
  }
}

export async function buildReportWorkbook(payload: ReportPayload): Promise<ExportResult> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "የኔ Go Admin";
  wb.created = new Date(payload.generatedAt);
  const periodLabel = periodRangeLabel(payload.period);

  // ---- Summary -----------------------------------------------------------
  const summary = wb.addWorksheet("Summary");
  addTitle(summary, "የኔ Go — Business Report", `Reporting period: ${periodLabel}`);
  summary.addRow([]);
  const metaRows: [string, string][] = [
    ["Platform", "የኔ Go"],
    ["Report period", periodLabel],
    ["Generated at", formatReportDateTime(payload.generatedAt)],
    ["Generated by", payload.generatedBy ?? "—"],
  ];
  for (const [label, value] of metaRows) {
    const row = summary.addRow([label, value]);
    row.getCell(1).font = { bold: true };
  }
  summary.addRow([]);
  summary.addRow(["Metric", "Value"]).font = { bold: true };
  const summaryStart = summary.rowCount;
  const metrics: [string, number | string, boolean][] = [
    ["Total orders", payload.summary.totalOrders, false],
    ["Completed orders", payload.summary.completedOrders, false],
    ["Pending orders", payload.summary.pendingOrders, false],
    ["Cancelled orders", payload.summary.cancelledOrders, false],
    ["Total sales (ETB)", payload.summary.totalSales, true],
    ["Delivery fees (ETB)", payload.summary.deliveryFees, true],
    ["Total payments (ETB)", payload.summary.totalPayments, true],
    ["Refunds (ETB)", payload.summary.refunds, true],
    ["Net revenue (ETB)", payload.summary.netRevenue, true],
    ["New customers", payload.summary.newCustomers, false],
    ["Active customers", payload.summary.activeCustomers, false],
    ["Shops", payload.summary.shops, false],
    ["Products", payload.summary.products, false],
    ["Rider orders", payload.summary.riderOrders, false],
  ];
  for (const [label, value, isMoney] of metrics) {
    const row = summary.addRow([label, value]);
    if (isMoney) row.getCell(2).numFmt = MONEY_FMT;
  }
  styleHeader(summary, 2, summaryStart);
  summary.getColumn(1).width = 30;
  summary.getColumn(2).width = 24;

  // ---- Orders ------------------------------------------------------------
  const orders = wb.addWorksheet("Orders");
  orders.columns = [
    { header: "Order ID", key: "orderCode", width: 16 },
    { header: "Date", key: "createdAt", width: 20 },
    { header: "Customer", key: "customer", width: 22 },
    { header: "Shop", key: "shop", width: 24 },
    { header: "Total (ETB)", key: "total", width: 14 },
    { header: "Payment method", key: "paymentMethod", width: 18 },
    { header: "Payment status", key: "paymentStatus", width: 16 },
    { header: "Order status", key: "status", width: 16 },
    { header: "Delivery status", key: "deliveryStatus", width: 16 },
    { header: "Rider", key: "rider", width: 20 },
  ];
  for (const o of payload.orders) {
    const row = orders.addRow({
      orderCode: o.orderCode,
      createdAt: new Date(o.createdAt),
      customer: o.customer,
      shop: o.shop,
      total: currency(o.total),
      paymentMethod: o.paymentMethod,
      paymentStatus: o.paymentStatus,
      status: statusLabel(o.status),
      deliveryStatus: o.deliveryStatus,
      rider: o.rider,
    });
    row.getCell("createdAt").numFmt = DATE_FMT;
    row.getCell("total").numFmt = MONEY_FMT;
  }
  styleHeader(orders, 10);
  addTotalRow(orders, "TOTAL", { 5: payload.orders.reduce((s, o) => s + o.total, 0) });

  // ---- Sales -------------------------------------------------------------
  const sales = wb.addWorksheet("Sales");
  sales.columns = [
    { header: "Period", key: "label", width: 18 },
    { header: "Orders", key: "orders", width: 12 },
    { header: "Gross sales (ETB)", key: "gross", width: 18 },
    { header: "Delivery fees (ETB)", key: "deliveryFees", width: 20 },
    { header: "Discounts (ETB)", key: "discounts", width: 16 },
    { header: "Refunds (ETB)", key: "refunds", width: 14 },
    { header: "Net sales (ETB)", key: "net", width: 18 },
  ];
  for (const point of payload.sales.points) {
    const row = sales.addRow({
      label: point.label,
      orders: point.orders,
      gross: currency(point.gross),
      deliveryFees: currency(point.deliveryFees),
      discounts: currency(point.discounts),
      refunds: currency(point.refunds),
      net: currency(point.net),
    });
    for (const col of ["gross", "deliveryFees", "discounts", "refunds", "net"]) {
      row.getCell(col).numFmt = MONEY_FMT;
    }
  }
  styleHeader(sales, 7);
  const salesTotals = payload.sales.totals;
  addTotalRow(sales, "TOTAL", {
    2: salesTotals.orders,
    3: salesTotals.gross,
    4: salesTotals.deliveryFees,
    5: salesTotals.discounts,
    6: salesTotals.refunds,
    7: salesTotals.net,
  });
  sales.addRow([]);
  sales.addRow(["Average order value (ETB)", salesTotals.avgOrderValue]).getCell(2).numFmt =
    MONEY_FMT;

  // ---- Payments ----------------------------------------------------------
  const payments = wb.addWorksheet("Payments");
  payments.columns = [
    { header: "Payment method", key: "label", width: 22 },
    { header: "Transactions", key: "transactions", width: 14 },
    { header: "Total amount (ETB)", key: "amount", width: 20 },
    { header: "Successful", key: "successful", width: 13 },
    { header: "Pending", key: "pending", width: 12 },
    { header: "Failed", key: "failed", width: 12 },
  ];
  for (const p of payload.payments) {
    const row = payments.addRow({ ...p, amount: currency(p.amount) });
    row.getCell("amount").numFmt = MONEY_FMT;
  }
  styleHeader(payments, 6);
  addTotalRow(payments, "TOTAL", {
    2: payload.payments.reduce((s, p) => s + p.transactions, 0),
    3: payload.payments.reduce((s, p) => s + p.amount, 0),
  });

  // ---- Shops -------------------------------------------------------------
  const shops = wb.addWorksheet("Shops");
  shops.columns = [
    { header: "Shop", key: "name", width: 28 },
    { header: "Orders", key: "orders", width: 12 },
    { header: "Sales (ETB)", key: "sales", width: 16 },
    { header: "Avg order value (ETB)", key: "avgOrderValue", width: 20 },
    { header: "Completed", key: "completed", width: 12 },
    { header: "Cancelled", key: "cancelled", width: 12 },
  ];
  for (const s of payload.shops) {
    const row = shops.addRow({
      ...s,
      sales: currency(s.sales),
      avgOrderValue: currency(s.avgOrderValue),
    });
    row.getCell("sales").numFmt = MONEY_FMT;
    row.getCell("avgOrderValue").numFmt = MONEY_FMT;
  }
  styleHeader(shops, 6);
  addTotalRow(shops, "TOTAL", {
    2: payload.shops.reduce((s, r) => s + r.orders, 0),
    3: payload.shops.reduce((s, r) => s + r.sales, 0),
  });

  // ---- Products ----------------------------------------------------------
  const products = wb.addWorksheet("Products");
  products.columns = [
    { header: "Product", key: "name", width: 30 },
    { header: "Shop", key: "shop", width: 26 },
    { header: "Units sold", key: "unitsSold", width: 12 },
    { header: "Revenue (ETB)", key: "revenue", width: 16 },
    { header: "Orders", key: "orders", width: 12 },
  ];
  for (const p of payload.products) {
    const row = products.addRow({ ...p, revenue: currency(p.revenue) });
    row.getCell("revenue").numFmt = MONEY_FMT;
  }
  styleHeader(products, 5);
  addTotalRow(products, "TOTAL", {
    3: payload.products.reduce((s, p) => s + p.unitsSold, 0),
    4: payload.products.reduce((s, p) => s + p.revenue, 0),
  });

  // ---- Customers ---------------------------------------------------------
  const customers = wb.addWorksheet("Customers");
  customers.columns = [
    { header: "Metric", key: "metric", width: 30 },
    { header: "Value", key: "value", width: 18 },
  ];
  const customerRows: [string, number, boolean][] = [
    ["Total customers", payload.customers.totalCustomers, false],
    ["New customers", payload.customers.newCustomers, false],
    ["Returning customers", payload.customers.returningCustomers, false],
    ["Orders in period", payload.customers.totalOrders, false],
    ["Total spending (ETB)", payload.customers.totalSpending, true],
  ];
  for (const [metric, value, isMoney] of customerRows) {
    const row = customers.addRow({ metric, value });
    if (isMoney) row.getCell("value").numFmt = MONEY_FMT;
  }
  styleHeader(customers, 2);

  // ---- Riders ------------------------------------------------------------
  const riders = wb.addWorksheet("Riders");
  riders.columns = [
    { header: "Rider", key: "name", width: 24 },
    { header: "Assigned orders", key: "assigned", width: 16 },
    { header: "Completed deliveries", key: "completed", width: 20 },
    { header: "Cancelled deliveries", key: "cancelled", width: 20 },
    { header: "Completion rate (%)", key: "completionRate", width: 18 },
  ];
  for (const r of payload.riders) {
    riders.addRow({ ...r });
  }
  styleHeader(riders, 5);
  addTotalRow(riders, "TOTAL", {
    2: payload.riders.reduce((s, r) => s + r.assigned, 0),
    3: payload.riders.reduce((s, r) => s + r.completed, 0),
    4: payload.riders.reduce((s, r) => s + r.cancelled, 0),
  });

  const buffer = await wb.xlsx.writeBuffer();
  return {
    filename: reportFileName(payload.period, "xlsx"),
    mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    base64: Buffer.from(buffer).toString("base64"),
  };
}
