/**
 * PDF export for the Reports system.
 *
 * Builds a print-ready business report (cover, executive summary, key stats,
 * sales / order / payment / shop / product tables and totals) from the same
 * `ReportPayload` the dashboard renders. Uses the platform's brand colour and
 * reuses the uploaded platform logo when one is configured.
 */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  formatReportDateTime,
  periodRangeLabel,
  reportFileName,
  statusLabel,
  type ReportPayload,
} from "@/lib/reports";
import type { ExportResult } from "@/lib/reports.functions";
import type { ReportClient } from "@/lib/reports.server";

// የኔ Go brand emerald.
const BRAND: [number, number, number] = [5, 150, 105];
const BRAND_DARK: [number, number, number] = [6, 95, 70];
const MUTED: [number, number, number] = [100, 116, 139];
const INK: [number, number, number] = [15, 23, 42];

const PAGE = { width: 595.28, height: 841.89, margin: 40 };
const CONTENT_WIDTH = PAGE.width - PAGE.margin * 2;

const money = (value: number) =>
  `${Number(value ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ETB`;

type Branding = { name: string; logo: string | null; city: string };

async function loadBranding(client: ReportClient): Promise<Branding> {
  const branding: Branding = { name: "የኔ Go", logo: null, city: "Bishoftu" };
  try {
    const { data } = await client
      .from("settings")
      .select("key,value")
      .in("key", ["site_content", "contact"]);
    const content = (data ?? []).find((r) => r.key === "site_content")?.value as
      Record<string, unknown> | undefined;
    if (content) {
      if (typeof content["brand_short_name"] === "string")
        branding.name = content["brand_short_name"];
      else if (typeof content["brand_name"] === "string") branding.name = content["brand_name"];
      if (typeof content["city"] === "string") branding.city = content["city"];
    }
    const logoPath = content && typeof content["logo_url"] === "string" ? content["logo_url"] : "";
    if (logoPath && !logoPath.startsWith("http")) {
      const { data: signed } = await client.storage
        .from("ligo-media")
        .createSignedUrl(logoPath, 300);
      if (signed?.signedUrl) {
        const res = await fetch(signed.signedUrl);
        if (res.ok) {
          const buf = Buffer.from(await res.arrayBuffer());
          branding.logo = `data:image/png;base64,${buf.toString("base64")}`;
        }
      }
    } else if (logoPath.startsWith("http")) {
      branding.logo = logoPath;
    }
  } catch (err) {
    console.warn("[reports] branding lookup failed, using defaults", err);
  }
  return branding;
}

export async function buildReportPdf(
  payload: ReportPayload,
  client: ReportClient,
): Promise<ExportResult> {
  const branding = await loadBranding(client);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const periodLabel = periodRangeLabel(payload.period);
  const generatedAt = formatReportDateTime(payload.generatedAt);
  let cursor = 0;

  // ---- Header band -------------------------------------------------------
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, PAGE.width, 96, "F");

  let textLeft = PAGE.margin;
  if (branding.logo) {
    try {
      doc.addImage(branding.logo, "PNG", PAGE.margin, 26, 44, 44);
      textLeft = PAGE.margin + 58;
    } catch {
      textLeft = PAGE.margin;
    }
  }
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(branding.name, textLeft, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Business Report", textLeft, 68);
  doc.setFontSize(9);
  doc.text(`${branding.city} · Fast. Local. Delivered.`, textLeft, 82);

  cursor = 120;
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Reporting period", PAGE.margin, cursor);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(periodLabel, PAGE.margin, cursor + 16);

  doc.setFontSize(9);
  const metaRight = `Generated: ${generatedAt}\nGenerated by: ${payload.generatedBy ?? "—"}`;
  doc.text(metaRight, PAGE.width - PAGE.margin, cursor, { align: "right" });
  cursor += 40;

  // ---- Executive summary -------------------------------------------------
  doc.setDrawColor(...BRAND);
  doc.setLineWidth(1);
  doc.line(PAGE.margin, cursor, PAGE.width - PAGE.margin, cursor);
  cursor += 22;
  doc.setTextColor(...BRAND_DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Executive summary", PAGE.margin, cursor);
  cursor += 18;

  doc.setTextColor(...INK);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const s = payload.summary;
  const summaryText =
    `${s.totalOrders.toLocaleString()} orders were placed during this period, ` +
    `${s.completedOrders.toLocaleString()} of them completed and ${s.cancelledOrders.toLocaleString()} cancelled. ` +
    `Delivered sales reached ${money(s.totalSales)} with ${money(s.deliveryFees)} in delivery fees, ` +
    `producing net revenue of ${money(s.netRevenue)}. ` +
    `${s.newCustomers.toLocaleString()} new customers joined and ${s.activeCustomers.toLocaleString()} customers were active.`;
  const summaryLines = doc.splitTextToSize(summaryText, CONTENT_WIDTH);
  doc.text(summaryLines, PAGE.margin, cursor);
  cursor += summaryLines.length * 14 + 16;

  // ---- Key statistics ----------------------------------------------------
  const statCards: [string, string][] = [
    ["Total orders", s.totalOrders.toLocaleString()],
    ["Completed", s.completedOrders.toLocaleString()],
    ["Pending", s.pendingOrders.toLocaleString()],
    ["Cancelled", s.cancelledOrders.toLocaleString()],
    ["Total sales", money(s.totalSales)],
    ["Delivery fees", money(s.deliveryFees)],
    ["Total payments", money(s.totalPayments)],
    ["Refunds", money(s.refunds)],
    ["Net revenue", money(s.netRevenue)],
    ["New customers", s.newCustomers.toLocaleString()],
    ["Active customers", s.activeCustomers.toLocaleString()],
    ["Rider orders", s.riderOrders.toLocaleString()],
  ];
  const cols = 3;
  const cardGap = 10;
  const cardWidth = (CONTENT_WIDTH - cardGap * (cols - 1)) / cols;
  const cardHeight = 46;
  statCards.forEach(([label, value], i) => {
    const col = i % cols;
    const rowIndex = Math.floor(i / cols);
    const x = PAGE.margin + col * (cardWidth + cardGap);
    const y = cursor + rowIndex * (cardHeight + cardGap);
    doc.setFillColor(236, 253, 245);
    doc.setDrawColor(...BRAND);
    doc.roundedRect(x, y, cardWidth, cardHeight, 6, 6, "FD");
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(label.toUpperCase(), x + 8, y + 16);
    doc.setTextColor(...INK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(value, x + 8, y + 34);
  });
  cursor += Math.ceil(statCards.length / cols) * (cardHeight + cardGap) + 10;

  // ---- Charts ------------------------------------------------------------
  // Lightweight native charts (no canvas dependency) so the PDF renders
  // identically on the server. Long ranges are folded into at most 12 points.
  const foldPoints = <T>(points: T[], size: number): T[][] => {
    if (points.length <= 12) return points.map((p) => [p]);
    const chunk = Math.ceil(points.length / 12);
    const groups: T[][] = [];
    for (let i = 0; i < points.length; i += chunk) groups.push(points.slice(i, i + chunk));
    return groups;
  };

  const salesPoints = payload.sales.points;
  if (salesPoints.some((p) => p.gross > 0 || p.orders > 0)) {
    const groups = foldPoints(salesPoints, 12);
    const series = groups.map((g) => ({
      label: g[0]!.label,
      gross: g.reduce((sum, p) => sum + p.gross, 0),
      orders: g.reduce((sum, p) => sum + p.orders, 0),
    }));
    const chartHeight = 150;
    if (cursor > PAGE.height - chartHeight - 60) {
      doc.addPage();
      cursor = PAGE.margin + 10;
    }
    const baseY = cursor + chartHeight;
    const maxGross = Math.max(...series.map((p) => p.gross), 1);
    const maxOrders = Math.max(...series.map((p) => p.orders), 1);
    const step = CONTENT_WIDTH / series.length;
    const barWidth = Math.min(step * 0.55, 26);

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(PAGE.margin, baseY, PAGE.width - PAGE.margin, baseY);

    series.forEach((point, i) => {
      const x = PAGE.margin + i * step + step / 2;
      const barH = (point.gross / maxGross) * (chartHeight - 20);
      doc.setFillColor(...BRAND);
      doc.rect(x - barWidth / 2, baseY - barH, barWidth, barH, "F");
      if (series.length <= 12) {
        doc.setTextColor(...MUTED);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(6.5);
        doc.text(point.label, x, baseY + 9, { align: "center" });
      }
    });

    // Orders trend line over the bars.
    doc.setDrawColor(15, 118, 110);
    doc.setLineWidth(1.5);
    let prev: [number, number] | null = null;
    series.forEach((point, i) => {
      const x = PAGE.margin + i * step + step / 2;
      const y = baseY - (point.orders / maxOrders) * (chartHeight - 20);
      if (prev) doc.line(prev[0], prev[1], x, y);
      doc.setFillColor(15, 118, 110);
      doc.circle(x, y, 1.6, "F");
      prev = [x, y];
    });

    doc.setTextColor(...BRAND_DARK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(
      `Sales by ${payload.sales.granularity} (bars) vs orders (line)`,
      PAGE.margin,
      cursor - 4,
    );
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(`peak sales ${money(maxGross)}`, PAGE.width - PAGE.margin, cursor - 4, {
      align: "right",
    });
    cursor = baseY + 24;
  }

  // Horizontal bar charts for status and payment mix.
  type HBarRow = { label: string; value: number; display: string };
  const drawHBar = (
    x: number,
    y: number,
    width: number,
    title: string,
    rows: HBarRow[],
    colour: [number, number, number],
  ) => {
    doc.setTextColor(...BRAND_DARK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(title, x, y);
    let rowY = y + 16;
    const max = Math.max(...rows.map((r) => r.value), 1);
    const labelWidth = 92;
    const barArea = width - labelWidth - 52;
    for (const row of rows) {
      doc.setTextColor(...INK);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.text(row.label, x, rowY + 7);
      const barW = Math.max((row.value / max) * barArea, row.value > 0 ? 2 : 0);
      doc.setFillColor(...colour);
      doc.rect(x + labelWidth, rowY, barW, 9, "F");
      doc.setTextColor(...MUTED);
      doc.setFontSize(7);
      doc.text(row.display, x + width, rowY + 7, { align: "right" });
      rowY += 15;
    }
    return rowY;
  };

  const statusRows: HBarRow[] = [
    {
      label: "Completed",
      value: payload.summary.completedOrders,
      display: String(payload.summary.completedOrders),
    },
    {
      label: "Pending",
      value: payload.summary.pendingOrders,
      display: String(payload.summary.pendingOrders),
    },
    {
      label: "Cancelled",
      value: payload.summary.cancelledOrders,
      display: String(payload.summary.cancelledOrders),
    },
  ];
  const paymentRows: HBarRow[] = payload.payments
    .filter((p) => p.transactions > 0)
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 4)
    .map((p) => ({ label: p.label, value: p.amount, display: money(p.amount) }));

  if (statusRows.some((r) => r.value > 0) || paymentRows.length) {
    const chartHeight = 16 + Math.max(statusRows.length, paymentRows.length, 1) * 15;
    if (cursor > PAGE.height - chartHeight - 60) {
      doc.addPage();
      cursor = PAGE.margin + 10;
    }
    const colWidth = (CONTENT_WIDTH - 24) / 2;
    const leftBottom = drawHBar(
      PAGE.margin,
      cursor,
      colWidth,
      "Orders by status",
      statusRows,
      BRAND,
    );
    const rightBottom = paymentRows.length
      ? drawHBar(
          PAGE.margin + colWidth + 24,
          cursor,
          colWidth,
          "Payments by method",
          paymentRows,
          [15, 118, 110],
        )
      : cursor;
    cursor = Math.max(leftBottom, rightBottom) + 16;
  }

  // ---- Tables ------------------------------------------------------------
  const startNewSection = (title: string) => {
    if (cursor > PAGE.height - 160) {
      doc.addPage();
      cursor = PAGE.margin + 10;
    }
    doc.setTextColor(...BRAND_DARK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(title, PAGE.margin, cursor);
    cursor += 8;
  };

  const tableTheme = {
    headStyles: {
      fillColor: BRAND,
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold" as const,
    },
    styles: { fontSize: 8.5, cellPadding: 5, textColor: INK },
    alternateRowStyles: { fillColor: [247, 250, 248] as [number, number, number] },
    margin: { left: PAGE.margin, right: PAGE.margin },
  };

  // Sales summary
  startNewSection(`Sales summary (by ${payload.sales.granularity})`);
  autoTable(doc, {
    ...tableTheme,
    startY: cursor,
    head: [["Period", "Orders", "Gross", "Delivery fees", "Discounts", "Net"]],
    body: payload.sales.points.map((p) => [
      p.label,
      String(p.orders),
      money(p.gross),
      money(p.deliveryFees),
      money(p.discounts),
      money(p.net),
    ]),
    foot: [
      [
        "TOTAL",
        String(payload.sales.totals.orders),
        money(payload.sales.totals.gross),
        money(payload.sales.totals.deliveryFees),
        money(payload.sales.totals.discounts),
        money(payload.sales.totals.net),
      ],
    ],
    footStyles: { fillColor: [231, 240, 234], textColor: INK, fontStyle: "bold" },
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
    },
  });
  cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

  // Payment summary
  startNewSection("Payment summary");
  autoTable(doc, {
    ...tableTheme,
    startY: cursor,
    head: [["Method", "Transactions", "Amount", "Successful", "Pending", "Failed"]],
    body: payload.payments.map((p) => [
      p.label,
      String(p.transactions),
      money(p.amount),
      String(p.successful),
      String(p.pending),
      String(p.failed),
    ]),
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
    },
  });
  cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

  // Order summary
  startNewSection(`Order summary (${payload.orders.length} orders)`);
  autoTable(doc, {
    ...tableTheme,
    startY: cursor,
    head: [["Order", "Date", "Customer", "Shop", "Total", "Payment", "Status", "Rider"]],
    body: payload.orders.map((o) => [
      o.orderCode,
      formatReportDateTime(o.createdAt),
      o.customer,
      o.shop,
      money(o.total),
      o.paymentMethod,
      statusLabel(o.status),
      o.rider,
    ]),
    columnStyles: { 4: { halign: "right" } },
  });
  cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

  // Shop performance
  if (payload.shops.length) {
    startNewSection("Shop performance");
    autoTable(doc, {
      ...tableTheme,
      startY: cursor,
      head: [["Shop", "Orders", "Sales", "Avg order", "Completed", "Cancelled"]],
      body: payload.shops.map((sh) => [
        sh.name,
        String(sh.orders),
        money(sh.sales),
        money(sh.avgOrderValue),
        String(sh.completed),
        String(sh.cancelled),
      ]),
      columnStyles: {
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
        4: { halign: "right" },
        5: { halign: "right" },
      },
    });
    cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;
  }

  // Product performance
  if (payload.products.length) {
    startNewSection("Product performance");
    autoTable(doc, {
      ...tableTheme,
      startY: cursor,
      head: [["Product", "Shop", "Units sold", "Revenue", "Orders"]],
      body: payload.products.map((p) => [
        p.name,
        p.shop,
        String(p.unitsSold),
        money(p.revenue),
        String(p.orders),
      ]),
      columnStyles: { 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } },
    });
    cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;
  }

  // Customer summary
  startNewSection("Customer summary");
  autoTable(doc, {
    ...tableTheme,
    startY: cursor,
    head: [["Metric", "Value"]],
    body: [
      ["Total customers", payload.customers.totalCustomers.toLocaleString()],
      ["New customers", payload.customers.newCustomers.toLocaleString()],
      ["Returning customers", payload.customers.returningCustomers.toLocaleString()],
      ["Orders in period", payload.customers.totalOrders.toLocaleString()],
      ["Total spending", money(payload.customers.totalSpending)],
    ],
    columnStyles: { 1: { halign: "right" } },
  });
  cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;

  // Rider performance
  if (payload.riders.length) {
    startNewSection("Rider performance");
    autoTable(doc, {
      ...tableTheme,
      startY: cursor,
      head: [["Rider", "Assigned", "Completed", "Cancelled", "Completion rate"]],
      body: payload.riders.map((r) => [
        r.name,
        String(r.assigned),
        String(r.completed),
        String(r.cancelled),
        `${r.completionRate}%`,
      ]),
      columnStyles: {
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
        4: { halign: "right" },
      },
    });
  }

  // ---- Footer on every page ---------------------------------------------
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(PAGE.margin, PAGE.height - 34, PAGE.width - PAGE.margin, PAGE.height - 34);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`${branding.name} · Business Report · ${periodLabel}`, PAGE.margin, PAGE.height - 20);
    doc.text(`Page ${i} of ${pageCount}`, PAGE.width - PAGE.margin, PAGE.height - 20, {
      align: "right",
    });
  }

  const output = doc.output("arraybuffer");
  return {
    filename: reportFileName(payload.period, "pdf"),
    mime: "application/pdf",
    base64: Buffer.from(output).toString("base64"),
  };
}
