/**
 * Server-safe report copy for English, Amharic and Afaan Oromoo.
 *
 * The Excel and PDF exports run on the server (and inside a server function)
 * where the client i18n dictionaries are not loaded. This module holds only
 * the strings those exports need, in all three languages, so a report is
 * produced in the admin's current language without importing the full UI
 * dictionary into the server bundle.
 */
import type { Language } from "@/lib/i18n";

export type ReportCopy = {
  businessReport: string;
  reportingPeriod: string;
  executiveSummary: string;
  generated: string;
  generatedBy: string;
  page: string;
  platform: string;
  reportPeriod: string;
  generatedAtLabel: string;
  metric: string;
  value: string;
  total: string;

  statTotalOrders: string;
  statCompleted: string;
  statPending: string;
  statCancelled: string;
  statTotalSales: string;
  statDeliveryFees: string;
  statTotalPayments: string;
  statRefunds: string;
  statNetRevenue: string;
  statNewCustomers: string;
  statActiveCustomers: string;
  statRiderOrders: string;

  summaryText: string;
  salesByGranularity: string;
  peakSales: string;
  ordersByStatus: string;
  paymentsByMethod: string;

  salesSummary: string;
  paymentSummary: string;
  orderSummary: string;
  shopPerformance: string;
  productPerformance: string;
  customerSummary: string;
  riderPerformance: string;

  colPeriod: string;
  colOrders: string;
  colGross: string;
  colDeliveryFees: string;
  colDiscounts: string;
  colNet: string;

  colMethod: string;
  colTransactions: string;
  colAmount: string;
  colSuccessful: string;
  colPending: string;
  colFailed: string;

  colOrder: string;
  colDate: string;
  colCustomer: string;
  colShop: string;
  colTotal: string;
  colPayment: string;
  colStatus: string;
  colRider: string;

  colSales: string;
  colAvgOrder: string;
  colCompleted: string;
  colCancelled: string;

  colProduct: string;
  colUnitsSold: string;
  colRevenue: string;

  colAssigned: string;
  colCompletionRate: string;

  custTotal: string;
  custNew: string;
  custReturning: string;
  custOrders: string;
  custSpending: string;

  sheetSummary: string;
  sheetOrders: string;
  sheetSales: string;
  sheetPayments: string;
  sheetShops: string;
  sheetProducts: string;
  sheetCustomers: string;
  sheetRiders: string;

  exTitle: string;
  exSubtitle: string;
  exTotal: string;
  exAvgOrderValue: string;

  /** Order status labels, keyed by the platform status id. */
  orderStatus: Record<string, string>;
  /** Payment method labels, keyed by the platform method id. */
  paymentMethod: Record<string, string>;
  /** Payment status labels, keyed by the platform status id. */
  paymentStatus: Record<string, string>;
  /** Delivery-stage labels derived from order status. */
  deliveryStatus: Record<string, string>;
};

const en: ReportCopy = {
  businessReport: "Business Report",
  reportingPeriod: "Reporting period",
  executiveSummary: "Executive summary",
  generated: "Generated",
  generatedBy: "Generated by",
  page: "Page",
  platform: "Platform",
  reportPeriod: "Report period",
  generatedAtLabel: "Generated at",
  metric: "Metric",
  value: "Value",
  total: "TOTAL",

  statTotalOrders: "Total orders",
  statCompleted: "Completed",
  statPending: "Pending",
  statCancelled: "Cancelled",
  statTotalSales: "Total sales",
  statDeliveryFees: "Delivery fees",
  statTotalPayments: "Total payments",
  statRefunds: "Refunds",
  statNetRevenue: "Net revenue",
  statNewCustomers: "New customers",
  statActiveCustomers: "Active customers",
  statRiderOrders: "Rider orders",

  summaryText:
    "{orders} orders were placed during this period, {completed} of them completed and {cancelled} cancelled. " +
    "Delivered sales reached {sales} with {fees} in delivery fees, producing net revenue of {net}. " +
    "{newCustomers} new customers joined and {activeCustomers} customers were active.",
  salesByGranularity: "Sales by {granularity} (bars) vs orders (line)",
  peakSales: "peak sales {amount}",
  ordersByStatus: "Orders by status",
  paymentsByMethod: "Payments by method",

  salesSummary: "Sales summary (by {granularity})",
  paymentSummary: "Payment summary",
  orderSummary: "Order summary ({count} orders)",
  shopPerformance: "Shop performance",
  productPerformance: "Product performance",
  customerSummary: "Customer summary",
  riderPerformance: "Rider performance",

  colPeriod: "Period",
  colOrders: "Orders",
  colGross: "Gross",
  colDeliveryFees: "Delivery fees",
  colDiscounts: "Discounts",
  colNet: "Net",

  colMethod: "Method",
  colTransactions: "Transactions",
  colAmount: "Amount",
  colSuccessful: "Successful",
  colPending: "Pending",
  colFailed: "Failed",

  colOrder: "Order",
  colDate: "Date",
  colCustomer: "Customer",
  colShop: "Shop",
  colTotal: "Total",
  colPayment: "Payment",
  colStatus: "Status",
  colRider: "Rider",

  colSales: "Sales",
  colAvgOrder: "Avg order",
  colCompleted: "Completed",
  colCancelled: "Cancelled",

  colProduct: "Product",
  colUnitsSold: "Units sold",
  colRevenue: "Revenue",

  colAssigned: "Assigned",
  colCompletionRate: "Completion rate",

  custTotal: "Total customers",
  custNew: "New customers",
  custReturning: "Returning customers",
  custOrders: "Orders in period",
  custSpending: "Total spending",

  sheetSummary: "Summary",
  sheetOrders: "Orders",
  sheetSales: "Sales",
  sheetPayments: "Payments",
  sheetShops: "Shops",
  sheetProducts: "Products",
  sheetCustomers: "Customers",
  sheetRiders: "Riders",

  exTitle: "{brand} — Business Report",
  exSubtitle: "Reporting period: {period}",
  exTotal: "TOTAL",
  exAvgOrderValue: "Average order value (ETB)",

  orderStatus: {
    pending_payment: "Pending Payment",
    confirmed: "Confirmed",
    preparing: "Preparing",
    ready_for_pickup: "Ready for Pickup",
    dispatched: "Dispatched",
    accepted: "Rider Accepted",
    arrived_at_merchant: "At Merchant",
    picked_up: "Picked Up",
    on_the_way: "On the Way",
    delivered: "Delivered",
    cancelled: "Cancelled",
  },
  paymentMethod: {
    cash: "Cash on delivery",
    mobile_money: "Mobile Money",
    telebirr: "Telebirr",
    cbe: "CBE Birr",
    boa: "Bank of Abyssinia",
    chapa: "Chapa",
  },
  paymentStatus: {
    unpaid: "Unpaid",
    pending: "Pending verification",
    pending_verification: "Pending verification",
    paid: "Paid",
    verified: "Verified",
    rejected: "Rejected",
    refunded: "Refunded",
  },
  deliveryStatus: {
    delivered: "Delivered",
    cancelled: "Cancelled",
    preparing: "Preparing",
    in_transit: "In transit",
    awaiting_payment: "Awaiting payment",
  },
};

const am: ReportCopy = {
  businessReport: "የቢዝነስ ሪፖርት",
  reportingPeriod: "የሪፖርት ጊዜ",
  executiveSummary: "የሥራ አስፈጻሚ ማጠቃለያ",
  generated: "የተመነጨ",
  generatedBy: "የተመነጨው በ",
  page: "ገጽ",
  platform: "መድረክ",
  reportPeriod: "የሪፖርት ጊዜ",
  generatedAtLabel: "የተመነጨበት ጊዜ",
  metric: "መለኪያ",
  value: "ዋጋ",
  total: "ጠቅላላ",

  statTotalOrders: "ጠቅላላ ትዕዛዞች",
  statCompleted: "የተጠናቀቁ",
  statPending: "በመጠባበቅ ላይ",
  statCancelled: "የተሰረዙ",
  statTotalSales: "ጠቅላላ ሽያጭ",
  statDeliveryFees: "የማድረስ ክፍያዎች",
  statTotalPayments: "ጠቅላላ ክፍያዎች",
  statRefunds: "ተመላሾች",
  statNetRevenue: "የተጣራ ገቢ",
  statNewCustomers: "አዲስ ደንበኞች",
  statActiveCustomers: "ንቁ ደንበኞች",
  statRiderOrders: "የራይደር ትዕዛዞች",

  summaryText:
    "በዚህ ጊዜ ውስጥ {orders} ትዕዛዞች ተሰጥተዋል፣ {completed} ተጠናቀዋል እና {cancelled} ተሰርዘዋል። " +
    "የተላለፈ ሽያጭ {sales} ደርሷል፣ ከዚህ ውስጥ {fees} የማድረስ ክፍያ ሲሆን የተጣራ ገቢ {net} ነው። " +
    "{newCustomers} አዲስ ደንበኞች ተቀላቅለዋል እና {activeCustomers} ደንበኞች ንቁ ነበሩ።",
  salesByGranularity: "ሽያጭ በ{granularity} (አሞሌዎች) እና ትዕዛዞች (መስመር)",
  peakSales: "ከፍተኛ ሽያጭ {amount}",
  ordersByStatus: "ትዕዛዞች በሁኔታ",
  paymentsByMethod: "ክፍያዎች በዘዴ",

  salesSummary: "የሽያጭ ማጠቃለያ (በ{granularity})",
  paymentSummary: "የክፍያ ማጠቃለያ",
  orderSummary: "የትዕዛዝ ማጠቃለያ ({count} ትዕዛዞች)",
  shopPerformance: "የሱቅ አፈጻጸም",
  productPerformance: "የምርት አፈጻጸም",
  customerSummary: "የደንበኛ ማጠቃለያ",
  riderPerformance: "የራይደር አፈጻጸም",

  colPeriod: "ጊዜ",
  colOrders: "ትዕዛዞች",
  colGross: "ጠቅላላ",
  colDeliveryFees: "የማድረስ ክፍያዎች",
  colDiscounts: "ቅናሾች",
  colNet: "የተጣራ",

  colMethod: "ዘዴ",
  colTransactions: "ግብይቶች",
  colAmount: "መጠን",
  colSuccessful: "ስኬታማ",
  colPending: "በመጠባበቅ ላይ",
  colFailed: "ያልተሳካ",

  colOrder: "ትዕዛዝ",
  colDate: "ቀን",
  colCustomer: "ደንበኛ",
  colShop: "ሱቅ",
  colTotal: "ጠቅላላ",
  colPayment: "ክፍያ",
  colStatus: "ሁኔታ",
  colRider: "ራይደር",

  colSales: "ሽያጭ",
  colAvgOrder: "አማካይ ትዕዛዝ",
  colCompleted: "የተጠናቀቁ",
  colCancelled: "የተሰረዙ",

  colProduct: "ምርት",
  colUnitsSold: "የተሸጡ ክፍሎች",
  colRevenue: "ገቢ",

  colAssigned: "የተመደቡ",
  colCompletionRate: "የማጠናቀቂያ መጠን",

  custTotal: "ጠቅላላ ደንበኞች",
  custNew: "አዲስ ደንበኞች",
  custReturning: "ተመላሽ ደንበኞች",
  custOrders: "በጊዜው ያሉ ትዕዛዞች",
  custSpending: "ጠቅላላ ወጪ",

  sheetSummary: "ማጠቃለያ",
  sheetOrders: "ትዕዛዞች",
  sheetSales: "ሽያጭ",
  sheetPayments: "ክፍያዎች",
  sheetShops: "ሱቆች",
  sheetProducts: "ምርቶች",
  sheetCustomers: "ደንበኞች",
  sheetRiders: "ራይደሮች",

  exTitle: "{brand} — የቢዝነስ ሪፖርት",
  exSubtitle: "የሪፖርት ጊዜ፦ {period}",
  exTotal: "ጠቅላላ",
  exAvgOrderValue: "አማካይ የትዕዛዝ ዋጋ (ETB)",

  orderStatus: {
    pending_payment: "በክፍያ በመጠበቅ",
    confirmed: "ተረጋግጧል",
    preparing: "በዝግጅት ላይ",
    ready_for_pickup: "ለመውሰድ ደርሷል",
    dispatched: "ተልኳል",
    accepted: "ራይደር ተቀብሏል",
    arrived_at_merchant: "መሸጫ ላይ",
    picked_up: "ተወስዷል",
    on_the_way: "በመንገድ ላይ",
    delivered: "ደርሷል",
    cancelled: "ተሰርዟል",
  },
  paymentMethod: {
    cash: "በደረሰኝ ጊዜ ጥሬ ገንዘብ",
    mobile_money: "የሞባይል ገንዘብ",
    telebirr: "ቴሌብር",
    cbe: "ሲቢኢ ብር",
    boa: "የአቢሲኒያ ባንክ",
    chapa: "ቻፓ",
  },
  paymentStatus: {
    unpaid: "ያልተከፈለ",
    pending: "ማረጋገጫ በመጠበቅ",
    pending_verification: "ማረጋገጫ በመጠበቅ",
    paid: "ተከፍሏል",
    verified: "ተረጋግጧል",
    rejected: "ውድቅ ሆኗል",
    refunded: "ተመላሽ ሆኗል",
  },
  deliveryStatus: {
    delivered: "ደርሷል",
    cancelled: "ተሰርዟል",
    preparing: "በዝግጅት ላይ",
    in_transit: "በመንገድ ላይ",
    awaiting_payment: "ክፍያ በመጠበቅ",
  },
};

const or: ReportCopy = {
  businessReport: "Gabaasa Daldalaa",
  reportingPeriod: "Yeroo gabaasaa",
  executiveSummary: "Cuunfaa hoji-raawwii",
  generated: "Kan maddisiise",
  generatedBy: "Kan maddisiise",
  page: "Fuula",
  platform: "Waltajjii",
  reportPeriod: "Yeroo gabaasaa",
  generatedAtLabel: "Yeroo maddisiise",
  metric: "Safartuu",
  value: "Gatii",
  total: "WALIIGALA",

  statTotalOrders: "Ajajoota waliigalaa",
  statCompleted: "Xumuraman",
  statPending: "Eegaa jiran",
  statCancelled: "Haqaman",
  statTotalSales: "Gurgurtaa waliigalaa",
  statDeliveryFees: "Kaffaltii geessuu",
  statTotalPayments: "Kaffaltiiwwan waliigalaa",
  statRefunds: "Deebistuu",
  statNetRevenue: "Galii qulqulluu",
  statNewCustomers: "Maamiltoota haaraa",
  statActiveCustomers: "Maamiltoota si'aa",
  statRiderOrders: "Ajajoota raayidaraa",

  summaryText:
    "Yeroo kana keessatti ajajoonni {orders} dhiyaatan, {completed} xumuraman, {cancelled} haqaman. " +
    "Gurgurtaan geesse {sales} ga'e, kaffaltiin geessuu {fees}, galii qulqulluun {net}. " +
    "Maamiltoonni haaraan {newCustomers} makaman, maamiltoonni {activeCustomers} si'aa turan.",
  salesByGranularity: "Gurgurtaa {granularity} (upright) fi ajajoota (line)",
  peakSales: "gurgurtaa ol'aanaa {amount}",
  ordersByStatus: "Ajajoota haalaan",
  paymentsByMethod: "Kaffaltiiwwan malaan",

  salesSummary: "Cuunfaa gurgurtaa ({granularity})",
  paymentSummary: "Cuunfaa kaffaltii",
  orderSummary: "Cuunfaa ajajaa (ajajoota {count})",
  shopPerformance: "Raawwii suuqa",
  productPerformance: "Raawwii oomishaa",
  customerSummary: "Cuunfaa maamilaa",
  riderPerformance: "Raawwii raayidaraa",

  colPeriod: "Yeroo",
  colOrders: "Ajajoota",
  colGross: "Waliigala",
  colDeliveryFees: "Kaffaltii geessuu",
  colDiscounts: "Hir'ina",
  colNet: "Qulqulluu",

  colMethod: "Mala",
  colTransactions: "Sochiiwwan",
  colAmount: "Maallaqa",
  colSuccessful: "Milkaa'aa",
  colPending: "Eegaa jira",
  colFailed: "Hin milkoofne",

  colOrder: "Ajaja",
  colDate: "Guyyaa",
  colCustomer: "Maamila",
  colShop: "Suuqa",
  colTotal: "Waliigala",
  colPayment: "Kaffaltii",
  colStatus: "Haala",
  colRider: "Raayidara",

  colSales: "Gurgurtaa",
  colAvgOrder: "Giddu-galeessa ajajaa",
  colCompleted: "Xumuraman",
  colCancelled: "Haqaman",

  colProduct: "Oomisha",
  colUnitsSold: "Kutaa gurguraman",
  colRevenue: "Galii",

  colAssigned: "Ramadaman",
  colCompletionRate: "Safara xumuraa",

  custTotal: "Maamiltoota waliigalaa",
  custNew: "Maamiltoota haaraa",
  custReturning: "Maamiltoota deebi'an",
  custOrders: "Ajajoota yeroo kana keessatti",
  custSpending: "Baasii waliigalaa",

  sheetSummary: "Cuunfaa",
  sheetOrders: "Ajajoota",
  sheetSales: "Gurgurtaa",
  sheetPayments: "Kaffaltiiwwan",
  sheetShops: "Suuqota",
  sheetProducts: "Oomishaalee",
  sheetCustomers: "Maamiltoota",
  sheetRiders: "Raayidaroota",

  exTitle: "{brand} — Gabaasa Daldalaa",
  exSubtitle: "Yeroo gabaasaa: {period}",
  exTotal: "WALIIGALA",
  exAvgOrderValue: "Giddu-galeessa gatii ajajaa (ETB)",

  orderStatus: {
    pending_payment: "Kaffaltii eegaa",
    confirmed: "Mirkanaa'e",
    preparing: "Qophaa'aa jira",
    ready_for_pickup: "Fudhachuuf qophii",
    dispatched: "Ergameera",
    accepted: "Rider fudhate",
    arrived_at_merchant: "Dukkaana irra",
    picked_up: "Fudhatameera",
    on_the_way: "Karaa irra",
    delivered: "Geesseera",
    cancelled: "Haqameera",
  },
  paymentMethod: {
    cash: "Yeroo geessu maallaqa harkaa",
    mobile_money: "Maallaqa mobaayilaa",
    telebirr: "Telebirr",
    cbe: "CBE Birr",
    boa: "Baankii Abisiiniyaa",
    chapa: "Chapa",
  },
  paymentStatus: {
    unpaid: "Hin kaffalamne",
    pending: "Mirkaneessa eegaa",
    pending_verification: "Mirkaneessa eegaa",
    paid: "Kaffalameera",
    verified: "Mirkanaa'eera",
    rejected: "Kufeera",
    refunded: "Deebi'ameera",
  },
  deliveryStatus: {
    delivered: "Geesse",
    cancelled: "Haqame",
    preparing: "Adeemsa keessa",
    in_transit: "Daandii irra",
    awaiting_payment: "Kaffaltii eegaa",
  },
};

export const REPORT_COPY: Record<Language, ReportCopy> = { en, am, or };

export function reportCopy(language: Language | undefined): ReportCopy {
  return REPORT_COPY[language ?? "en"] ?? REPORT_COPY.en;
}

/** Replace `{name}` placeholders in a report copy string. */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? ""));
}
