/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountHelpRouteImport } from './routes/account.help'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFinancialsRouteImport } from './routes/admin.financials'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as MerchantJoinRouteImport } from './routes/merchant.join'
import { Route as MerchantLoginRouteImport } from './routes/merchant.login'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as RiderJoinRouteImport } from './routes/rider.join'
import { Route as RiderLoginRouteImport } from './routes/rider.login'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as SpecialMomentsIndexRouteImport } from './routes/special-moments.index'
import { Route as SpecialMomentsSearchRouteImport } from './routes/special-moments.search'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as AccountServiceRequestsIndexRouteImport } from './routes/account.service-requests.index'
import { Route as AccountServiceRequestsRequestIdRouteImport } from './routes/account.service-requests.$requestId'
import { Route as SpecialMomentsCategorySlugRouteImport } from './routes/special-moments.category.$slug'
import { Route as SpecialMomentsServiceServiceIdRouteImport } from './routes/special-moments.service.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHelpRoute = AccountHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialsRoute = AdminFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRoute,
} as any)
const MerchantJoinRoute = MerchantJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MerchantRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderJoinRoute = RiderJoinRouteImport.update({
  id: '/rider/join',
  path: '/rider/join',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderLoginRoute = RiderLoginRouteImport.update({
  id: '/rider/login',
  path: '/rider/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialMomentsIndexRoute = SpecialMomentsIndexRouteImport.update({
  id: '/special-moments/',
  path: '/special-moments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialMomentsSearchRoute = SpecialMomentsSearchRouteImport.update({
  id: '/special-moments/search',
  path: '/special-moments/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)
const AccountServiceRequestsIndexRoute =
  AccountServiceRequestsIndexRouteImport.update({
    id: '/service-requests/',
    path: '/service-requests/',
    getParentRoute: () => AccountRoute,
  } as any)
const AccountServiceRequestsRequestIdRoute =
  AccountServiceRequestsRequestIdRouteImport.update({
    id: '/service-requests/$requestId',
    path: '/service-requests/$requestId',
    getParentRoute: () => AccountRoute,
  } as any)
const SpecialMomentsCategorySlugRoute =
  SpecialMomentsCategorySlugRouteImport.update({
    id: '/special-moments/category/$slug',
    path: '/special-moments/category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpecialMomentsServiceServiceIdRoute =
  SpecialMomentsServiceServiceIdRouteImport.update({
    id: '/special-moments/service/$serviceId',
    path: '/special-moments/service/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/help': typeof AccountHelpRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/merchant/join': typeof MerchantJoinRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/rider/join': typeof RiderJoinRoute
  '/rider/login': typeof RiderLoginRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/special-moments/search': typeof SpecialMomentsSearchRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/special-moments/': typeof SpecialMomentsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/service-requests/$requestId': typeof AccountServiceRequestsRequestIdRoute
  '/special-moments/category/$slug': typeof SpecialMomentsCategorySlugRoute
  '/special-moments/service/$serviceId': typeof SpecialMomentsServiceServiceIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/service-requests/': typeof AccountServiceRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/help': typeof AccountHelpRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/merchant/join': typeof MerchantJoinRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/rider/join': typeof RiderJoinRoute
  '/rider/login': typeof RiderLoginRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/special-moments/search': typeof SpecialMomentsSearchRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/rider': typeof RiderIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/special-moments': typeof SpecialMomentsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/service-requests/$requestId': typeof AccountServiceRequestsRequestIdRoute
  '/special-moments/category/$slug': typeof SpecialMomentsCategorySlugRoute
  '/special-moments/service/$serviceId': typeof SpecialMomentsServiceServiceIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/account/service-requests': typeof AccountServiceRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/help': typeof AccountHelpRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/merchant/join': typeof MerchantJoinRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/rider/join': typeof RiderJoinRoute
  '/rider/login': typeof RiderLoginRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/special-moments/search': typeof SpecialMomentsSearchRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/special-moments/': typeof SpecialMomentsIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/service-requests/$requestId': typeof AccountServiceRequestsRequestIdRoute
  '/special-moments/category/$slug': typeof SpecialMomentsCategorySlugRoute
  '/special-moments/service/$serviceId': typeof SpecialMomentsServiceServiceIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/service-requests/': typeof AccountServiceRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/offers'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/account/addresses'
    | '/account/help'
    | '/account/notifications'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/financials'
    | '/admin/login'
    | '/admin/map'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/riders'
    | '/merchant/join'
    | '/merchant/login'
    | '/orders/$orderId'
    | '/rider/join'
    | '/rider/login'
    | '/shops/$shopId'
    | '/special-moments/search'
    | '/account/'
    | '/admin/'
    | '/orders/'
    | '/rider/'
    | '/shops/'
    | '/special-moments/'
    | '/account/orders/$orderId'
    | '/account/service-requests/$requestId'
    | '/special-moments/category/$slug'
    | '/special-moments/service/$serviceId'
    | '/account/orders/'
    | '/account/service-requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/offers'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/account/addresses'
    | '/account/help'
    | '/account/notifications'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/financials'
    | '/admin/login'
    | '/admin/map'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/riders'
    | '/merchant/join'
    | '/merchant/login'
    | '/orders/$orderId'
    | '/rider/join'
    | '/rider/login'
    | '/shops/$shopId'
    | '/special-moments/search'
    | '/account'
    | '/admin'
    | '/orders'
    | '/rider'
    | '/shops'
    | '/special-moments'
    | '/account/orders/$orderId'
    | '/account/service-requests/$requestId'
    | '/special-moments/category/$slug'
    | '/special-moments/service/$serviceId'
    | '/account/orders'
    | '/account/service-requests'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/offers'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/account/addresses'
    | '/account/help'
    | '/account/notifications'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/financials'
    | '/admin/login'
    | '/admin/map'
    | '/admin/ops'
    | '/admin/reports'
    | '/admin/riders'
    | '/merchant/join'
    | '/merchant/login'
    | '/orders/$orderId'
    | '/rider/join'
    | '/rider/login'
    | '/shops/$shopId'
    | '/special-moments/search'
    | '/account/'
    | '/admin/'
    | '/orders/'
    | '/rider/'
    | '/shops/'
    | '/special-moments/'
    | '/account/orders/$orderId'
    | '/account/service-requests/$requestId'
    | '/special-moments/category/$slug'
    | '/special-moments/service/$serviceId'
    | '/account/orders/'
    | '/account/service-requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  RiderJoinRoute: typeof RiderJoinRoute
  RiderLoginRoute: typeof RiderLoginRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  SpecialMomentsSearchRoute: typeof SpecialMomentsSearchRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  SpecialMomentsIndexRoute: typeof SpecialMomentsIndexRoute
  SpecialMomentsCategorySlugRoute: typeof SpecialMomentsCategorySlugRoute
  SpecialMomentsServiceServiceIdRoute: typeof SpecialMomentsServiceServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/help': {
      id: '/account/help'
      path: '/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof AccountHelpRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financials': {
      id: '/admin/financials'
      path: '/financials'
      fullPath: '/admin/financials'
      preLoaderRoute: typeof AdminFinancialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/merchant/join': {
      id: '/merchant/join'
      path: '/join'
      fullPath: '/merchant/join'
      preLoaderRoute: typeof MerchantJoinRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/login': {
      id: '/merchant/login'
      path: '/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/join': {
      id: '/rider/join'
      path: '/rider/join'
      fullPath: '/rider/join'
      preLoaderRoute: typeof RiderJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/login': {
      id: '/rider/login'
      path: '/rider/login'
      fullPath: '/rider/login'
      preLoaderRoute: typeof RiderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-moments/': {
      id: '/special-moments/'
      path: '/special-moments'
      fullPath: '/special-moments/'
      preLoaderRoute: typeof SpecialMomentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-moments/search': {
      id: '/special-moments/search'
      path: '/special-moments/search'
      fullPath: '/special-moments/search'
      preLoaderRoute: typeof SpecialMomentsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/service-requests/': {
      id: '/account/service-requests/'
      path: '/service-requests'
      fullPath: '/account/service-requests/'
      preLoaderRoute: typeof AccountServiceRequestsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/service-requests/$requestId': {
      id: '/account/service-requests/$requestId'
      path: '/service-requests/$requestId'
      fullPath: '/account/service-requests/$requestId'
      preLoaderRoute: typeof AccountServiceRequestsRequestIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/special-moments/category/$slug': {
      id: '/special-moments/category/$slug'
      path: '/special-moments/category/$slug'
      fullPath: '/special-moments/category/$slug'
      preLoaderRoute: typeof SpecialMomentsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-moments/service/$serviceId': {
      id: '/special-moments/service/$serviceId'
      path: '/special-moments/service/$serviceId'
      fullPath: '/special-moments/service/$serviceId'
      preLoaderRoute: typeof SpecialMomentsServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountHelpRoute: typeof AccountHelpRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountServiceRequestsRequestIdRoute: typeof AccountServiceRequestsRequestIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
  AccountServiceRequestsIndexRoute: typeof AccountServiceRequestsIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountHelpRoute: AccountHelpRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountServiceRequestsRequestIdRoute: AccountServiceRequestsRequestIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
  AccountServiceRequestsIndexRoute: AccountServiceRequestsIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminFinancialsRoute: typeof AdminFinancialsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinancialsRoute: AdminFinancialsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMapRoute: AdminMapRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantJoinRoute: typeof MerchantJoinRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantJoinRoute: MerchantJoinRoute,
  MerchantLoginRoute: MerchantLoginRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  RiderJoinRoute: RiderJoinRoute,
  RiderLoginRoute: RiderLoginRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  SpecialMomentsSearchRoute: SpecialMomentsSearchRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  SpecialMomentsIndexRoute: SpecialMomentsIndexRoute,
  SpecialMomentsCategorySlugRoute: SpecialMomentsCategorySlugRoute,
  SpecialMomentsServiceServiceIdRoute: SpecialMomentsServiceServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
